global:
  hosts:
    domain: gitlab-stand.cyber.pg
    gitlab:
      name: gitlab-stand.cyber.pg
  ingress:
    enabled: true
    tls:
      enabled: false
    configureCertmanager: false

certmanager-issuer:
  email: gitlab@cyber.pg
# Отключение мониторинга
monitoring:
  enabled: false
prometheus:
  enabled: false
  install: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    enabled: false

gitlab:
  upgradeCheck:
    enabled: false

  webservice:
    replicaCount: 2
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "1"
        memory: "3Gi"
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 5
      failureThreshold: 5
    extraEnv:
      SKIP_DOUBLE_INIT: "true"
      PUMA_WORKERS: "2"
      PUMA_THREADS: "4"
      DISABLE_PUMA_WORKER_KILLER: "false"

# Остальные настройки
postgresql:
  install: true
  persistence:
    size: 20Gi

redis:
  install: true
  persistence:
    size: 10Gi

gitlab-runner:
  install: true
