global:
  hosts:
    domain: gitlab-stand.cyber.pg
    gitlab:
      name: gitlab-stand.cyber.pg
  ingress:
    enabled: true
    tls:
      enabled: false
    configureCertmanager: false

certmanager-issuer:
  email: gitlab@cyber.pg

monitoring:
  enabled: false
prometheus:
  enabled: false
  install: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    enabled: false

gitlab:
  upgradeCheck:
    enabled: false

  webservice:
    replicaCount: 2
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "1"
        memory: "3Gi"
    
    extraEnv:
      SKIP_DOUBLE_INIT: "true"
      PUMA_WORKERS: "2"
      PUMA_THREADS: "4"
      DISABLE_PUMA_WORKER_KILLER: "false"
      PUMA_SINGLE_MODE: "false"
      RAILS_ENV: "production"
      MALLOC_ARENA_MAX: "2"
    
    livenessProbe:
      httpGet:
        path: /-/health
        port: 8080
      initialDelaySeconds: 180
      periodSeconds: 10
      timeoutSeconds: 5
    
    readinessProbe:
      httpGet:
        path: /-/readiness
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 3
    
    redis:
      host: "gitlab-system-redis-master.gitlab.svc.cluster.local"
      port: 6379
      password:
        enabled: true
        secret: "gitlab-system-redis-secret"
        key: "secret"
    
    puma:
      workerTimeout: 60
      workerShutdownTimeout: 30
    
    initContainers:
      configure: false
      certificates: false

postgresql:
  install: true
  persistence:
    size: 20Gi

redis:
  install: true
  persistence:
    size: 10Gi
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

gitlab-runner:
  install: true
