global:
  hosts:
    domain: gitlab-stand.pg
    gitlab:
      name: gitlab-stand.pg
  ingress:
    enabled: true
    tls:
      enabled: false
    configureCertmanager: false
    annotations:
      kubernetes.io/ingress.class: nginx

# Полное отключение всех компонентов cert-manager
certmanager:
  enabled: true
  installCRDs: true
  rbac:
    create: true
  webhook:
    enabled: true  # Явное отключение webhook

certmanager-issuer:
  enabled: true

# Отключение всех RBAC-ресурсов
rbac:
  create: true

# Остальные настройки
postgresql:
  install: true
  persistence:
    size: 20Gi

redis:
  install: true
  persistence:
    size: 10Gi

gitlab-runner:
  install: true
  runners:
    privileged: true
