global:
  hosts:
    domain: gitlab-stand.pg
    gitlab:
      name: gitlab-stand.pg
  ingress:
    enabled: true
    tls:
      enabled: false  # Полностью отключаем TLS
    configureCertmanager: false  # Критически важная настройка
    annotations:
      kubernetes.io/ingress.class: nginx

# Полное отключение всех компонентов cert-manager
certmanager:
  enabled: false  # Вместо install: false
  installCRDs: false
certmanager-issuer:
  enabled: false

# Отключение RBAC-ресурсов
rbac:
  create: false

# Остальные настройки
postgresql:
  install: true
  persistence:
    size: 20Gi

redis:
  install: true
  persistence:
    size: 10Gi

gitlab-runner:
  install: true
  runners:
    privileged: true
