# Основные настройки
global:
  hosts:
    domain: gitlab-stand.pg       # Ваш домен (например, gitlab.your-company.com)
    gitlab:
      name: gitlab-stand.pg # Полный адрес GitLab
  ingress:
    enabled: true
    tls:
      enabled: true               # Включить TLS (HTTPS)
      secretName: gitlab-tls      # Имя секрета с сертификатом (можно создать через cert-manager)
    annotations:
      kubernetes.io/ingress.class: nginx  # Или ваш Ingress-контроллер (traefik, istio и т. д.)

# БД и Redis (можно вынести во внешние сервисы)
postgresql:
  install: true                  # Встроенный PostgreSQL
  persistence:
    size: 20Gi                   # Размер диска

redis:
  install: true
  persistence:
    size: 10Gi

# GitLab Runner (опционально)
gitlab-runner:
  install: true
  runners:
    privileged: true             # Нужно для Docker-in-Docker (DinD)

# Доп. настройки
gitlab:
  webservice:
    replicas: 2                 # Кол-во реплик
  sidekiq:
    replicas: 2
