global:
  hosts:
    domain: gitlab-stand.cyber.pg
    gitlab:
      name: gitlab-stand.cyber.pg
  ingress:
    enabled: true
    tls:
      enabled: false
    configureCertmanager: false

certmanager-issuer:
  email: gitlab@cyber.pg
# Отключение мониторинга
monitoring:
  enabled: false
prometheus:
  enabled: false
  install: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    enabled: false

gitlab:
  upgradeCheck:
    enabled: false

# Остальные настройки
postgresql:
  install: true
  persistence:
    size: 20Gi

redis:
  install: true
  persistence:
    size: 10Gi

gitlab-runner:
  install: true

nginx-ingress:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
        ssh: 30222
