apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-webservice
  namespace: gitlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitlab-webservice
  template:
    metadata:
      labels:
        app: gitlab-webservice
    spec:
      containers:
      - name: webservice
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://gitlab-stand.cyber.pg'
            gitlab_rails['db_adapter'] = 'postgresql'
            gitlab_rails['db_host'] = 'gitlab-postgresql'
            gitlab_rails['db_password'] = "$(POSTGRES_PASSWORD)"
            gitlab_rails['redis_host'] = 'gitlab-redis'
            gitlab_rails['redis_password'] = "$(REDIS_PASSWORD)"
        envFrom:
        - secretRef:
            name: gitlab-secrets
