apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    version: "7.0.0" # Укажите актуальную версию
    values:
      global:
        hosts:
          domain: gitlab-stand.cyber.pg
          https: false # Если нет TLS
        ingress:
          enabled: true
          configureCertmanager: false
      certmanager:
        install: false
      postgresql:
        install: true
      redis:
        install: true
      gitlab:
        gitlab-exporter:
          enabled: false
        webservice:
          replicas: 1
        sidekiq:
          replicas: 1
        toolbox:
          enabled: true
