apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-controller-manager
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        image: registry.gitlab.com/gitlab-org/cloud-native/gitlab-operator:v0.8.0
        args:
        - "--enable-leader-election"
        - "--metrics-addr=:8080"
        - "--zap-log-level=info"
        volumeMounts:
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: webhook-certs
        hostPath:
          path: /tmp/k8s-webhook-server/serving-certs
          type: Directory
      terminationGracePeriodSeconds: 10
